### ISSUE TITLE
measure-lambda-cold-starts removes environment variables after completing

### ISSUE THREAD

**Issue by drissamri** [lumigo-io/lumigo-CLI#107]
measure-lambda-cold-starts works perfectly but afterwards the existing environment variables are removed and replaced with a single one: `uuid` 

This makes the function fail after the analysis is complete: 
<img width="1284" alt="Schermafbeelding 2020-10-03 om 17 42 33" src="https://user-images.githubusercontent.com/2703192/95016078-002d0480-0651-11eb-9755-e8c30660dfbe.png">
<img width="1288" alt="Schermafbeelding 2020-10-03 om 18 11 49" src="https://user-images.githubusercontent.com/2703192/95016084-06bb7c00-0651-11eb-9531-0e92fa0e966a.png">

**Comment by theburningmonk** [comment]
@drissamri this should be fixed now, can you try again?

**Comment by drissamri** [comment]
Fixed, thank you very much!
