### ISSUE TITLE
Stackoscope (feature request)

### ISSUE THREAD

**Issue by dobeerman** [lumigo-io/lumigo-CLI#121]
Hi there,

Lumigo CLI is AWSome tool. Thanks for it ;)

Recently, you have introduced the `Stackoscope` for this tool that generates a quite helpful PDF report.

**The question is**: Would it make sense to add an option to generate a XML or CSV file to give an ability for users to easily create a todo lists of improvements?

Currently, we have a 19 pages of improvements suggested by Stackoscope and it's quite hard to copy/paste all resources to todo :D 

Thanks ;)

**Comment by efimk-lu** [comment]
Great idea. Adding it to our internal plan

**Comment by efimk-lu** [comment]
@dobeerman just released a new version to include CSV.
