### ISSUE TITLE
Tail DynamoDB Stream from the dynamodb-local docker image

### ISSUE THREAD

**Issue by j0k3r** [lumigo-io/lumigo-CLI#23]
The `tail-dynamo` command is really great.

Is it possible to have it tail stream when using the DynamoDB Local Docker image https://hub.docker.com/r/amazon/dynamodb-local ?

**Comment by theburningmonk** [comment]
Do you know if DynamoDB local supports streams? If so, and it has a local HTTP endpoint that you can configure the DynamoDB Streams client with then yes, it's possible to support dynamodb local.

**Comment by j0k3r** [comment]
Yep it supports stream and the HTTP endpoint is usually `http://localhost:8000` (you define the port when running the docker image). Credentials & region don't matter.

**Comment by theburningmonk** [comment]
Ok, in that case it should be simply a case of letting you pass in the endpoint to the AWS SDK client
