### ISSUE TITLE
Decode Kinesis stream messages

### ISSUE THREAD

**Issue by Binjaaa** [lumigo-io/lumigo-CLI#24]
Currently, the messages are gzipped and base64 encoded. Displayed as the following:

![image](https://user-images.githubusercontent.com/2379007/66754504-077e5f80-ee8e-11e9-8bd5-cf843a8f3122.png)

**Comment by theburningmonk** [comment]
How are you publishing the data?

**Comment by theburningmonk** [comment]
Oh wait, are the data coming from CloudWatch Logs?

**Comment by Binjaaa** [comment]
> Oh wait, are the data coming from CloudWatch Logs?

Yes, logs are from CloudWatch

**Comment by theburningmonk** [comment]
@Binjaaa try the latest version `0.14.0`, should handle zipped content and JSON payload better now
