### ISSUE TITLE
Support for role_arn / source_profile format in AWS Credentials file

### ISSUE THREAD

**Issue by chromalley** [lumigo-io/lumigo-CLI#37]
I tried taking the Lumigo-CLI for a spin today and found an issue wherein I am not able to use a profile that assumes a role from a base AWS account. The format in the credentials file looks like this: 

```
[dev]
role_arn = arn:aws:iam::999633339999:role/poweruser_role
source_profile = some-profile
```

The error I get back is:

```
Replacing [default] profile creds with [dev] creds
Error: No "dev" profile found. Please check your creds
    at replaceDefaultProfile (~/.nvm/versions/node/v10.16.3/lib/node_modules/lumigo-cli/node_modules/aws-profile-utils/lib/index.js:103:11)
    at SwitchProfileCommand.run (~/.nvm/versions/node/v10.16.3/lib/node_modules/lumigo-cli/src/commands/switch-profile.js:48:5)
```

Note that this type of profile definition is supported by the AWS CLI.

**Comment by theburningmonk** [comment]
@efimk-lu were you able to take a look at this? if not, I can pick it up instead

**Comment by efimk-lu** [comment]
No, go ahead
