### ISSUE TITLE
bug: Slack Hook cannot be set up

### ISSUE THREAD

**Issue by decebal** [lumigo-io/lumigo-CLI#52]

**Comment by theburningmonk** [comment]
@decebal I don't follow, we don't have any commands for setting up slack hooks. Can you elaborate on the problem?

**Comment by aviadmor** [comment]
I think he is referring to slack integration in the Lumigo platform. We are
assisting him directly.

Aviad Mor

CTO & Co-Founder
 | *M:* +972.52.720.6727 |  *E:* *aviad@lumigo.io <aviad@lumigo.io>* | [image:
linkedin-icon_square_16x16.png] <https://www.linkedin.com/in/aviadmor/> [image:
twitter-icon_square_16x16.png] <https://twitter.com/AviadMor>

**Comment by decebal** [comment]
Sorry for the confusion, I used the cli to submit this issue and was not sure where it will end up. I got the necessary assistance, thanks @aviadmor .

**Comment by theburningmonk** [comment]
@decebal no worries, glad that you got it sorted!
