### ISSUE TITLE
list-kinesis-streams hangs when there are no streams anywhere

### ISSUE THREAD

**Issue by theburningmonk** [lumigo-io/lumigo-CLI#64]

**Comment by efimk-lu** [comment]
@theburningmonk can you share the command that you used?

**Comment by theburningmonk** [comment]
@efimk-lu I just ran `lumigo-cli list-kinesis-streams` and it hang after the message `Checking Kinesis streams in all regions`

**Comment by theburningmonk** [comment]
mm.. I just ran it again and now it returned an empty table. Not sure what was different that time

**Comment by theburningmonk** [comment]
Let's close it for now since I can't reproduce it anymore
