### ISSUE TITLE
bug: replaySqs having UnsupportedOperation

### ISSUE THREAD

**Issue by Goaty89** [lumigo-io/lumigo-CLI#94]
I am new to lumigo-cli. Was try to replay sqs from dlq to normal queue, error occur 'AWS.SimpleQueueService.UnsupportedOperation: Message attribute list values in SendMessageBatch operation are not supported.'

I am using temporary role as my credentials. 
v0.45.0

**Comment by JordanSinko** [comment]
I can validate this is happening with version 0.45 but worked on 0.25.2.

**Comment by theburningmonk** [comment]
thank you guys, I will have a look
